name: "AzVmRunCommand"
description: "This action uses az vm run-command in order to execute a command in the target VM, check the result and fail the build if it didn't execute properly. Requires being logged into azure through the azure login action"
inputs:
  commandName:
    description: "Name of the command to execute"
    required: true
  script:
    description: "The script to execute"
    required: true
runs:
  using: "composite"
  steps:      
    - name: Execute the command
      uses: azure/CLI@v1
      with:
        inlineScript: |
          az vm run-command create \
            --resource-group $rgName \
            --vm-name $vmName \
            --name "${{ inputs.commandName }}" \
            --script "${{ inputs.script }}"
            
    - name: Get the result of the command
      uses: azure/CLI@v1
      with:
        inlineScript: |
          az vm run-command show \
            --resource-group $rgName \
            --vm-name $vmName \
            --name "${{ inputs.commandName }}" \
            --instance-view
